# .readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - pip install poetry
    install:
      - make install_dev
    post_install:
      - make build_docs

sphinx:
  configuration: docs/conf.py
