# .readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - pip install poetry
    install:
      - poetry install --with docs
    post_install:
      - poetry run sphinx-build -b html docs/ docs/_build/html

sphinx:
  configuration: docs/conf.py
